import { NAME } from './constants'

export const SHOW = `${NAME}/SHOW`
export const UPDATE_MAIN_POPUP_MSG = `${NAME}/UPDATE_MAIN_POPUP_MSG`
export const CLOSE_MAIN_POPUP = `${NAME}/CLOSE_MAIN_POPUP`
export const UPDATE_PRODLIST = `${NAME}/UPDATE_PRODLIST`
export const UPDATE_FETCH_APIURL = `${NAME}/UPDATE_FETCH_APIURL`
export const UPDATE_CUSTOMER_INFO = `${NAME}/UPDATE_CUSTOMER_INFO`
export const TARGET_ACCOUNT = `${NAME}/TARGET_ACCOUNT`
export const TOGGLE_CHANGE_POPUP = `${NAME}/TOGGLE_CHANGE_POPUP`
export const UPDATE_EXCHANGE = `${NAME}/UPDATE_EXCHANGE`
