import { NAME } from './constants'

export const NEW = `${NAME}/NEW`
export const CHANGE_ORDER_STATUS = `${NAME}/CHANGE_ORDER_STATUS`
export const SHOW_ORDER_QUOTE = `${NAME}/SHOW_ORDER_QUOTE`
export const UPDATE_TICK = `${NAME}/UPDATE_TICK`
export const BID_AND_ASK_TICK = `${NAME}/BID_AND_ASK_TICK`
export const CLEAR_ORDER = `${NAME}/CLEAR_ORDER`
export const CHECK_DELETE_ROW = `${NAME}/CHECK_DELETE_ROW`
export const ADD_DEAL_HISTORY = `${NAME}/ADD_DEAL_HISTORY`
export const INFLAT_DEAL_HISTORY = `${NAME}/INFLAT_DEAL_HISTORY`
export const UPDATE_ORDER_LIST_HISTORY = `${NAME}/UPDATE_ORDER_LIST_HISTORY`
export const CLEAR_QUOTE = `${NAME}/CLEAR_QUOTE`
